swagger: "2.0"
info:
  title: TwoLine API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://www.amonster.net/
  contact:
    email: apple@amonster.net
basePath: /v1
paths:
  /users/{uid}:
    get:
      tags:
      - users
      description: 获取用户信息
      operationId: UsersController.Get
      parameters:
      - in: path
        name: uid
        description: 用户ID
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: :uid 为空
        "401":
          description: 未登录或登录已过期
        "404":
          description: :uid 不存在
  /users/login:
    post:
      tags:
      - users
      description: 登录或注册
      operationId: UsersController.Login
      parameters:
      - in: query
        name: phonenumber
        description: 手机号
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.LoginResponseJSON'
        "400":
          description: 缺少参数
  /users/logout:
    get:
      tags:
      - users
      description: 退出登录，销毁 sessionID
      operationId: UsersController.logout
      responses:
        "200":
          description: '{nil} logout success'
        "401":
          description: 未登录或登录已过期
definitions:
  controllers.LoginResponseJSON:
    title: LoginResponseJSON
    type: object
    properties:
      isNewUser:
        type: boolean
      sessionID:
        type: string
  models.User:
    title: User
    type: object
    properties:
      avatarURL:
        type: string
      certificationTime:
        type: string
        format: datetime
      createTime:
        type: string
        format: datetime
      firstUploadAvatarTime:
        type: string
        format: datetime
      id:
        type: integer
        format: int64
      idCardAvatarURL:
        type: string
      idCardNo:
        type: string
      isFriend:
        type: boolean
      isSubscribed:
        type: boolean
      name:
        type: string
      phoneNumber:
        type: string
      subscriptionCount:
        type: integer
        format: int64
      updateTime:
        type: string
        format: datetime
      yunxinID:
        type: string
tags:
- name: users
  description: |
    Operations about Users
